# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.ImageField(upload_to='pictures/%Y/%m/%d'),
        ),
    ]
