# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avator',
            field=models.ImageField(blank=True, default='avators/default.png', upload_to='avators'),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='new player', max_length=40),
        ),
    ]
