# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160317_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(default='Secret', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='New Player', max_length=40),
        ),
    ]
