# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametemporarytable',
            name='vid',
            field=models.IntegerField(default=0, verbose_name='vid'),
        ),
    ]
